
CC = clang
CFLAGS = -Wall -Werror

.PHONY: all
all: gen quickSort quickSortInsertion1 quickSortInsertion2

gen: gen.c
quickSort: quickSort.c
quickSortInsertion1: quickSortInsertion1.c
quickSortInsertion2: quickSortInsertion2.c

.PHONY: clean
clean:
	rm -f gen quickSort quickSortInsertion1 quickSortInsertion2

