
CC = clang
CFLAGS = -Wall -Werror

.PHONY: all
all: linearSearch timeLinearSearch binarySearch timeBinarySearch

linearSearch: linearSearch.c
timeLinearSearch: timeLinearSearch.c
binarySearch: binarySearch.c
timeBinarySearch: timeBinarySearch.c

.PHONY: clean
clean:
	rm -f linearSearch timeLinearSearch binarySearch timeBinarySearch
