
CC = clang
CFLAGS = -Wall -Werror -g -fsanitize=address,leak,undefined

all: factorial listSum listAppend listAppend2 printNumberedList fib

factorial: factorial.c
listSum: listSum.c
listAppend: listAppend.c
listAppend2: listAppend2.c
printNumberedList: printNumberedList.c
fib: fib.c

clean:
	rm -f factorial listSum listAppend listAppend2 printNumberedList fib
